// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/ship": {
            "get": {
                "description": "returns ships",
                "produces": [
                    "application/json"
                ],
                "summary": "GetShips",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Channel name",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ChannelsResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "creates new ship",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "CreateShip",
                "parameters": [
                    {
                        "description": "VK Channel",
                        "name": "vk_channel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateVKChannelRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.IDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/ship/{id}": {
            "get": {
                "description": "returns ship by id",
                "produces": [
                    "application/json"
                ],
                "summary": "GetShipByID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ChannelResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "deletes ship by id",
                "summary": "DeleteShip",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "updates ship",
                "consumes": [
                    "application/json"
                ],
                "summary": "UpdateShip",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "VK Channel",
                        "name": "vk_channel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.PatchVKChannelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "health check",
                "produces": [
                    "text/plain"
                ],
                "summary": "HealthCheck",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "returns service metrics",
                "produces": [
                    "application/json"
                ],
                "summary": "Metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.MetricsResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ChannelResponse": {
            "type": "object",
            "properties": {
                "channel_name": {
                    "type": "string"
                },
                "channel_type": {
                    "type": "string"
                },
                "channel_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "site_url": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "api.ChannelsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storage.VKChannel"
                    }
                }
            }
        },
        "api.CreateVKChannelRequest": {
            "type": "object",
            "properties": {
                "channel_name": {
                    "type": "string"
                },
                "channel_type": {
                    "type": "string"
                },
                "channel_url": {
                    "type": "string"
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "api.IDResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "api.MetricsResponse": {
            "type": "object",
            "properties": {
                "avg_req": {
                    "$ref": "#/definitions/metrix.AvgReqData"
                },
                "current_req": {
                    "$ref": "#/definitions/metrix.CurrentReqData"
                },
                "db_metrix": {
                    "$ref": "#/definitions/metrix.DbMetrixData"
                },
                "resp_time": {
                    "$ref": "#/definitions/metrix.RespTimeData"
                }
            }
        },
        "api.PatchVKChannelRequest": {
            "type": "object",
            "properties": {
                "channel_name": {
                    "type": "string"
                },
                "channel_type": {
                    "type": "string"
                },
                "channel_url": {
                    "type": "string"
                },
                "site_url": {
                    "type": "string"
                }
            }
        },
        "metrix.AvgReqData": {
            "type": "object",
            "properties": {
                "fifteen_min_avg_req": {
                    "type": "number"
                },
                "five_min_avg_req": {
                    "type": "number"
                },
                "one_min_avg_req": {
                    "type": "number"
                }
            }
        },
        "metrix.CurrentReqData": {
            "type": "object",
            "properties": {
                "current_req_num": {
                    "type": "integer"
                }
            }
        },
        "metrix.DbMetrixData": {
            "type": "object",
            "properties": {
                "acquire_count": {
                    "description": "AcquireCount returns the cumulative count of successful acquires from the pool.",
                    "type": "integer"
                },
                "acquire_duration": {
                    "description": "AcquireDuration returns the total duration of all successful acquires from\nthe pool.",
                    "type": "integer"
                },
                "acquired_conns": {
                    "description": "AcquiredConns returns the number of currently acquired connections in the pool.",
                    "type": "integer"
                },
                "canceled_acquire_count": {
                    "description": "CanceledAcquireCount returns the cumulative count of acquires from the pool\nthat were canceled by a context.",
                    "type": "integer"
                },
                "constructing_conns": {
                    "description": "ConstructingConns returns the number of conns with construction in progress in\nthe pool.",
                    "type": "integer"
                },
                "empty_acquire_count": {
                    "description": "EmptyAcquireCount returns the cumulative count of successful acquires from the pool\nthat waited for a resource to be released or constructed because the pool was\nempty.",
                    "type": "integer"
                },
                "idle_conns": {
                    "description": "IdleConns returns the number of currently idle conns in the pool.",
                    "type": "integer"
                },
                "max_conns": {
                    "description": "MaxConns returns the maximum size of the pool.",
                    "type": "integer"
                },
                "max_idle_destroy_count": {
                    "description": "MaxIdleDestroyCount returns the cumulative count of connections destroyed because\nthey exceeded MaxConnIdleTime.",
                    "type": "integer"
                },
                "max_lifetime_destroy_count": {
                    "description": "MaxLifetimeDestroyCount returns the cumulative count of connections destroyed\nbecause they exceeded MaxConnLifetime.",
                    "type": "integer"
                },
                "new_conns_count": {
                    "description": "NewConnsCount returns the cumulative count of new connections opened.",
                    "type": "integer"
                },
                "total_conns": {
                    "description": "TotalConns returns the total number of resources currently in the pool.\nThe value is the sum of ConstructingConns, AcquiredConns, and\nIdleConns.",
                    "type": "integer"
                }
            }
        },
        "metrix.RespTimeData": {
            "type": "object",
            "properties": {
                "fifteen_min_avg_resp_time": {
                    "type": "number"
                },
                "five_min_avg_resp_time": {
                    "type": "number"
                },
                "one_min_avg_resp_time": {
                    "type": "number"
                }
            }
        },
        "storage.VKChannel": {
            "type": "object",
            "properties": {
                "channel_name": {
                    "type": "string"
                },
                "channel_type": {
                    "type": "string"
                },
                "channel_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "site_url": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Find Ship API",
	Description:      "This is a vk channles site parser.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
