{{- $connString := printf "postgres://%s:%s@%s:%v/%s?connect_timeout=%v&sslmode=disable&search_path=%s" .Values.db.user .Values.db.password .Values.db.host .Values.db.port .Values.db.name .Values.db.connect_timeout .Values.db.search_path -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-password: {{ .Values.db.password | b64enc | quote }}
  postgres-connection-string: {{ $connString | b64enc | quote }}
